version: "3.9"
services:
  database:
    image: postgres:latest
    networks:
      - backend
    restart: always
    ports:
      - "5432:5432"
    container_name: ktor_database
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ktor_database

  server:
    image: amazoncorretto:17.0.5
    networks:
      - backend
    restart: always
    ports:
      - "3000:3000"
    container_name: ktor_server
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - "database"
    command: ./gradlew run

networks:
  backend:
    driver: bridge

volumes:
  pg-data: { }