version: "3.9"
services:

  server:
    build: .
    networks:
      - backend
    restart: always
    ports:
      - "3000:3000"
    container_name: ktor_server
    volumes:
      - .:/app:z
      - .gradle:/root/.gradle:z
    working_dir: /app
    depends_on:
      - database
    command: bash ./gradlew run

  database:
    image: postgres:latest
    networks:
      - backend
    restart: always
    ports:
      - "5432:5432"
    container_name: ktor_database
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ktor_database

networks:
  backend:

volumes:
  pg-data: { }