#
# Copyright (c) 2022 CristianMg <https://github.com/CristianMG>
#   National Electronics and Computer Technology Center, Thailand
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

version: "3.9"

services:
  server:
    networks:
      - backend
    restart: always
    # THIS BIT!!!1!
    container_name: ktor_server
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:latest
    networks:
      - backend
    restart: always
    ports:
      - "5432:5432"
    container_name: ktor_database
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ktor_database

networks:
  backend:
    external: true

volumes:
  pg-data: { }