name: Build release version

on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto

      - name: Test core test
        run: make test

      - name: Result tests core
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "backend/build/test-results/**/*.xml"